#!/bin/bash

DATE=$(date +"%Y%m%d_%H%M%S")
ROTATE=10
CLASSIFIER="default"
ROOM="default"
INPUTDIR=""
EXCLUDE=""
OUTPUTDIR=/home/filesbackups
FTP_HOST=""
FTP_PORT="21"
FTP_USER=""
FTP_PWD=""

for i in "$@"
do
case $i in
    -f=*|--classifier=*)
    CLASSIFIER="${i#*=}"
    shift # past argument=value
    ;;
    -r=*|--rotate=*)
    ROTATE="${i#*=}"
    shift # past argument=value
    ;;
    -c=*|--crondir=*)
    ROOM="${i#*=}"
    shift # past argument=value
    ;;
    -i=*|--input=*)
    INPUTDIR="${i#*=}"
    shift # past argument=value
    ;;
    -e=*|--exclude=*)
    EXCLUDE="${i#*=}"
    shift # past argument=value
    ;;
    -o=*|--output=*)
    OUTPUTDIR="${i#*=}"
    shift # past argument=value
    ;;
    -u=*|--ftpuser=*)
    FTP_USER="${i#*=}"
    shift # past argument=value
    ;;
    -w=*|--ftppwd=*)
    FTP_PWD="${i#*=}"
    shift # past argument=value
    ;;
    -s=*|--ftphost=*)
    FTP_HOST="${i#*=}"
    shift # past argument=value
    ;;
    -t=*|--ftpport=*)
    FTP_PORT="${i#*=}"
    shift # past argument=value
    ;;
    -h|--help)
    echo "Usage: dumprotate2 [-options]"
    echo "where options include:"
    echo "	-f | --classifier	project name for exemple (will be a root directory for all your dumps)"
    echo "	-r | --rotate		rotate counter (e.g: -r='10', default: $ROTATE)"
    echo "	-c | --crondir		cron directory, useful when you want to store dump in many ways  (e.g: -c='hourly', default: $ROOM)"
    echo "	-i | --input		input directory, location where dumps are initially stored (e.g: -i='/home/mybucket')"
    echo "	-e | --exclude	exclude directories from input directory separated by ; (e.g: -e='/home/mybucket/.git;/home/mybucket/cache')"
    echo "	-o | --output		output directory, location where dumps will be stored (e.g: -o='/home/filesbackups')"
    echo "  	-u | --ftpuser		ftp username"
    echo "	-w | --ftppwd		ftp password"
    echo "	-s | --ftphost	ftp host"
    echo "	-t | --ftpport		ftp port"
    echo "	-h | --help		shows this help"
    exit 0
    ;;
    *)
          # unknown option
    ;;
esac
done

for EXCLUDE_ITEM in $(echo $EXCLUDE | tr ";" "\n")
do
    EXCLUDE_CMD="$EXCLUDE_CMD --exclude='$EXCLUDE_ITEM' "
done

if [[ ! $ROTATE =~ ^[0-9]+$ ]]; then
      echo "Error: -r=*|--rotate=* parameter must be a number" && exit 1
fi

if [[ ! $ROOM =~ ^[a-zA-Z0-9_]+$ ]]; then
      echo "Error: -c=*|--crondir=* parameter must be a lowercase word" && exit 1
fi

echo "======= START"
echo "Source Directory: $INPUTDIR"
echo "Working Directory: $OUTPUTDIR"
echo "Rotate Counter: $ROTATE"
echo "Classifier Name: $CLASSIFIER"
echo "Room Name: $ROOM"
echo "FTP Host: $FTP_HOST"
echo "FTP Port: $FTP_PORT"
echo "FTP User: $FTP_USER"
echo "======="

echo "Dump dir: $INPUTDIR"
 
createDir() {
    ftp -n $FTP_HOST $FTP_PORT <<END_SCRIPT
quote USER $FTP_USER
quote PASS $FTP_PWD
mkdir $CLASSIFIER
mkdir $CLASSIFIER/$ROOM
quit
END_SCRIPT
}

uploadBackup() {
    ftp -n $FTP_HOST $FTP_PORT <<END_SCRIPT
quote USER $FTP_USER
quote PASS $FTP_PWD
binary
put $1 $2
quit
END_SCRIPT
}

deleteFile() {
    ftp -n $FTP_HOST $FTP_PORT <<END_SCRIPT
quote USER $FTP_USER
quote PASS $FTP_PWD
delete $1
quit
END_SCRIPT
}

mkdir -p $OUTPUTDIR/$CLASSIFIER/$ROOM
createDir

RELATIVE_OUTPUTFILE="$CLASSIFIER/$ROOM/filesbackups_$CLASSIFIER_$DATE.tar"
OUTPUTFILE="$OUTPUTDIR/$RELATIVE_OUTPUTFILE"

_tar=$(tar $EXCLUDE_CMD -Pzcf $OUTPUTFILE $INPUTDIR)
uploadBackup $OUTPUTFILE $RELATIVE_OUTPUTFILE

counter=$(find $OUTPUTDIR/$CLASSIFIER/$ROOM/ -maxdepth 1 -type f | wc -l)
#echo "Dump counter: $counter"

dumps=$(ls -1 $OUTPUTDIR/$CLASSIFIER/$ROOM/ | sort -r)
cpt=0
for dump in $dumps
do
	((cpt+=1))
	if [ $cpt -gt $ROTATE ]
	then
		#echo "REMOVE FILE $cpt/$ROTATE"
		rm $OUTPUTDIR/$CLASSIFIER/$ROOM/$dump
		deleteFile $CLASSIFIER/$ROOM/$dump
	fi
done


echo "======= END"
